### ISSUE TITLE
How to participate?

### ISSUE THREAD

**Issue by kLiHz** [Computer-Literacy-Primer/Computer-Literacy-Primer#4]
I found this project meaningful and haven't seen any other similar project for the time being. Is it possible for me or maybe someone else to help contribute to this project?

**Comment by alissa-tung** [comment]
Thank you for issuing! This project is indeed needing a hacking guide for newcomers. It is recommended to join our Telegram group if you want to contribute to this project now. It is proposed written in simplified Chinese and one of the goals is to fit itself in the environment of mainland China well.

**Comment by kLiHz** [comment]
It's good to receive your reply! I have no idea why I chose to ask in English in the first place😂, but I'm actually a sophomore in Computer Science just from China mainland. Maybe I will be able to help! 😊

**Comment by alissa-tung** [comment]
> It's good to receive your reply! I have no idea why I chose to ask in English in the first placejoy, but I'm actually a sophomore in Computer Science just from China mainland. Maybe I will be able to help! blush

cc @ksyx

**Comment by ksyx** [comment]
Nice to learn about that! Feel free to tell us which topic would you like to pick up and just start working on. ❤️ 

Due to heavy course load of most members, the progress of this project might be a bit slow and please be aware of that. Thanks again for your contribution to the project~

**Comment by kLiHz** [comment]
> Thank you for issuing! This project is indeed needing a hacking guide for newcomers. It is recommended to join our Telegram group if you want to contribute to this project now. It is proposed written in simplified Chinese and one of the goals is to fit itself in the environment of mainland China well.

I'm really appreciated for all your patient reply! So, how could I join your Telegram group? Or maybe I can just open PRs?

**Comment by ksyx** [comment]
Yeah opening PRs directly is compeletely welecomed as long as you tell us what you would like to contribute in advance to avoid working on the same content. I have mailed our QQ group number to you and please contact me on TG at _ksyxmeow_ for telegram group invitation link. The two groups are connected by bot so joining any one is okay!

Welcome joining us!

**Comment by kLiHz** [comment]
@ksyx So sorry for not checking my mailbox and bring such trouble! I've seen your email and made my reply. Thanks a lot!
